// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using georgecarlinwebsite.Models;

namespace georgecarlinwebsite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("georgecarlinwebsite.Models.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentText");

                    b.Property<int?>("CommenterUserID");

                    b.Property<int?>("StoryID");

                    b.HasKey("CommentID");

                    b.HasIndex("CommenterUserID");

                    b.HasIndex("StoryID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("georgecarlinwebsite.Models.Story", b =>
                {
                    b.Property<int>("StoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.Property<string>("UserStory");

                    b.HasKey("StoryID");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("georgecarlinwebsite.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("StoryID");

                    b.HasKey("UserID");

                    b.HasIndex("StoryID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("georgecarlinwebsite.Models.Comment", b =>
                {
                    b.HasOne("georgecarlinwebsite.Models.User", "Commenter")
                        .WithMany("Comments")
                        .HasForeignKey("CommenterUserID");

                    b.HasOne("georgecarlinwebsite.Models.Story")
                        .WithMany("Comments")
                        .HasForeignKey("StoryID");
                });

            modelBuilder.Entity("georgecarlinwebsite.Models.User", b =>
                {
                    b.HasOne("georgecarlinwebsite.Models.Story")
                        .WithMany("Users")
                        .HasForeignKey("StoryID");
                });
#pragma warning restore 612, 618
        }
    }
}
